
name: Deploy to GitHub Pages via angular-cli-ghpages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Use Node.js 16.x
         uses: actions/setup-node@v1
         with:
           node-version: 16.x

       - name: Prepare and deploy
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
           # find src/ -name "*.scss" -exec sed -i "s@/assets@assets@" {} \;
           sh process_images.sh
           npm install
           npm run ng -- deploy --cname=mariuszkiepura.com --name="Actions Bot" --email="fabio4335@gmail.com"
